### ISSUE TITLE
IDE download link forbidden (yields 403)

### ISSUE THREAD

**Issue by btreut** [kprasadvnsi/tang-doc#8]
The download link on page https://github.com/kprasadvnsi/tang-doc/blob/master/content/getting-started/requirements/_index.en.md pointing to http://dl.sipeed.com/TANG/Primer/IDE/ yields an error 403 (forbidden).

**Comment by kprasadvnsi** [comment]
Thanks for reporting this issue. It's been fixed in commit [1acea3f](https://github.com/kprasadvnsi/tang-doc/commit/1acea3fcf44115c19c51683187d832dc85cf3d11)

**Comment by btreut** [comment]
Dear Kail, thanks a lot ...
